# Generated by Django 6.0.2 on 2026-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
    ]
