# Generated by Django 5.2.8 on 2026-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Subaru', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
